version: '3.4'

services:
  # apitrinus:
  #   image: apitrinus
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on: 
  #     - db
  db:
    image: postgres
    env_file:
      - ./database/env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 65432:5432
